# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

AWSTemplateFormatVersion: 2010-09-09
Description: Amazon Kendra Documents Refresher

Parameters:
  BucketNamePrefix:
    Description: S3 Bucket name
    Type: String
    Default: kendra-workshop

Resources:

  WorkshopsKendraRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "KendrasRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "kendra.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: KendrasPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: "Allow"
              Action: 
                - "kendra:BatchPutDocument"
                - "kendra:BatchDeleteDocument"
              Resource: "*"
            - Effect: "Allow"
              Action: 
                - "s3:GetObject"
                - "s3:ListBucket"
              Resource: "*"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"

  WorkshopKendraIndex:
    Type: "AWS::Kendra::Index"
    Properties:
      Name: "WorkshopKendraIndex"
      Description: Workshop Kendra Index
      RoleArn: !GetAtt WorkshopsKendraRole.Arn
      Edition: "DEVELOPER_EDITION"
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W80
            reason: Amazon Kendra will encrypt your data with Amazon Kendra owned key by default

  KendraDataSource:
    Type: AWS::Kendra::DataSource
    Properties: 
      DataSourceConfiguration: 
        S3Configuration: 
          BucketName: !Ref WorkshopBucket
      IndexId: !Ref WorkshopKendraIndex
      Name: "KendraDataSource"
      LanguageCode: "ko"
      RoleArn: !GetAtt WorkshopsKendraRole.Arn
      Type: "S3"

  WorkshopBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', [!Ref BucketNamePrefix, !Select [2, !Split ['/', !Ref AWS::StackId]]]]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: S3 access logging is not required since no sensitive documents are used for this blog

  WorkshopBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WorkshopBucket
      PolicyDocument:
        Statement:
          - Sid: AllowSSLRequestsOnly
            Action:
              - s3:*
            Effect: Deny
            Resource:
              - !Join ['-', [!Sub 'arn:${AWS::Partition}:s3:::${BucketNamePrefix}', !Select [2, !Split ['/', !Ref AWS::StackId]]]]
              - !Join ['/', [!Join ['-', [!Sub 'arn:${AWS::Partition}:s3:::${BucketNamePrefix}', !Select [2, !Split ['/', !Ref AWS::StackId]]]], '*']]
            Principal: '*'
            Condition:
              Bool:
                'aws:SecureTransport': false

Outputs:
  S3Bucket:
    Description: S3 Bucket that stores workshop documents
    Value: !Ref WorkshopBucket
  KendraIndex:
    Description: Kendra index id
    Value: !GetAtt WorkshopKendraIndex.Id
