AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the infrastructure for SageMaker Studio to communicate with Redshift Serverless
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Required Parameters for Setup
        Parameters:
          - ProjectName
          - DatabaseName
          - VpcCIDR
          - PublicSubnet1CIDR
          - PrivateSubnet1CIDR
          - PrivateSubnet2CIDR
          - PrivateSubnet3CIDR
    ParameterLabels:
      ProjectName:
        default: Project Name
      DatabaseName:
        default: Database Name
      VpcCIDR:
        default: Vpc CIDR
      PublicSubnet1CIDR:
        default: Public Subnet 1 CIDR
      PrivateSubnet1CIDR:
        default: Private Subnet 1 CIDR
      PrivateSubnet2CIDR:
        default: Private Subnet 2 CIDR
      PrivateSubnet3CIDR:
        default: Private Subnet 3 CIDR

Parameters:
  ProjectName:
    Description: SageMaker Studio project name
    Type: String
    Default: sagemaker-studio
  DatabaseName:
    Description: Redshift serverless database name
    Type: String
    Default: dev
  StudioDomainName:
    Description: SageMaker Studio domain name
    Type: String
    Default: workshop-domain
  StudioUserProfileName:
    Description: SageMaker Studio user profile name
    Type: String
    Default: workshop-user
  VpcCIDR:
    Description: VPC CIDR
    Type: String
    Default: 10.1.0.0/16
  PublicSubnet1CIDR:
    Description: VPC public subnet 1 CIDR
    Type: String
    Default: 10.1.1.0/24
  PrivateSubnet1CIDR:
    Description: VPC private subnet 1 CIDR
    Type: String
    Default: 10.1.2.0/24
  PrivateSubnet2CIDR:
    Description: VPC private subnet 2 CIDR
    Type: String
    Default: 10.1.3.0/24
  PrivateSubnet3CIDR:
    Description: VPC private subnet 3 CIDR
    Type: String
    Default: 10.1.4.0/24

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
        PrivateSubnet3CIDR: !Ref PrivateSubnet3CIDR
      TemplateURL: https://retaildemostore-base-rmtqij67oxpv-clo-webuibucket-pd8maaxyy2nk.s3.us-east-1.amazonaws.com/workshop_cloudformation/sm-studio-vpc.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJBJM3TXZANY6SKFA%2F20231113%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231113T012337Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=a89e6d42e13c0675dfcdab2b37e36335a04106be4e3c1467210d4ac4059131d4
  
  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://retaildemostore-base-rmtqij67oxpv-clo-webuibucket-pd8maaxyy2nk.s3.us-east-1.amazonaws.com/workshop_cloudformation/sm-studio-iam.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJBJM3TXZANY6SKFA%2F20231116%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231116T054437Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=ff714365bd8c09ed3d233664a101205b2442fef4dde36bcd2085a3e75681c78b

  SageMaker:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DomainName: !Ref StudioDomainName
        UserProfileName: !Ref StudioUserProfileName
        ExecutionRoleArn: !GetAtt IAM.Outputs.ExecutionRoleArn
        VpcId: !GetAtt VPC.Outputs.VpcId
        SubnetIds: !GetAtt VPC.Outputs.SubnetIds
        SecurityGroups: !GetAtt VPC.Outputs.SageMakerSecurityGroup
      TemplateURL: https://retaildemostore-base-rmtqij67oxpv-clo-webuibucket-pd8maaxyy2nk.s3.us-east-1.amazonaws.com/workshop_cloudformation/sm-studio-domain.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJBJM3TXZANY6SKFA%2F20231113%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231113T012510Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=10866e937363a7513975f8cfdd4024af5d5f4dc9f3df6583d13999e081b53d31

  Redshift:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        # ProjectName: !Ref ProjectName
        DatabaseName: !Ref DatabaseName
        SubnetId: !GetAtt VPC.Outputs.SubnetIds
        SecurityGroupIds: !GetAtt VPC.Outputs.RedshiftSecurityGroup
        IAMRole: !GetAtt IAM.Outputs.ExecutionRoleArn
      TemplateURL: https://retaildemostore-base-rmtqij67oxpv-clo-webuibucket-pd8maaxyy2nk.s3.us-east-1.amazonaws.com/workshop_cloudformation/rsserverless-setup.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJBJM3TXZANY6SKFA%2F20231113%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231113T012550Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=4b8305d9c346ad642f29f4b6f478e6cbdcf4201ea1e9d79b6407cce3b9006153

  Kendra:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://retaildemostore-base-rmtqij67oxpv-clo-webuibucket-pd8maaxyy2nk.s3.us-east-1.amazonaws.com/workshop_cloudformation/kendra-setup.yml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJBJM3TXZANY6SKFA%2F20231116%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231116T051925Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=6eaf2a83cf2693c7f363e03e69dca5d4b10a6ac12dadd0a0a1cc30fce7ecaaf2
